turno_app/turno_app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls import handler404, handler500
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('status/', views.status, name='status'),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('turnos/', include(('turnos.urls', 'turnos'), namespace='turnos')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'turno_app.views.page_no_found'
handler500 = 'turno_app.views.page_no_found'

turno_app/users/urls.py
from django.urls import path
from users import views 

urlpatterns = [
    path(
        route= 'login', 
        view= views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout', 
        view= views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup',
        view = views.SignupView.as_view(),
        name='signup')
    ,
    path(
        route='me',
        view= views.UpdateProfileView.as_view(), 
        name='update_profile'
    ),

    path(
        route='<str:username>/',
        view = views.UserDetailView.as_view(),
        name='detail'
    )
]

turno_app/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from turnos.models import Empresa

class Profile(models.Model):

    ASESOR='ASESOR'
    ADMIN='ADMIN'
    CLIENT='CLIENT'
    ROLES = (
        (ASESOR, 'Asesor'),
        (ADMIN, 'Administrador'),
        (CLIENT, 'Cliente')
    )

    # Proxy user atuh    
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    empresa = models.ForeignKey(Empresa,on_delete=models.CASCADE)
    website = models.URLField(max_length = 200,blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20,blank=True)
    picture = models.ImageField(
        upload_to='users/pictures', 
        blank=True,
        null=True
    )
    rol = models.CharField(max_length=100, choices=ROLES, default=ASESOR)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.user.username

turno_app/users/forms.py
from django import forms
from django.contrib.auth.models import User
from users.models import Profile


class SignupForm(forms.Form):
    """Sign up form."""

    username = forms.CharField(min_length=4, max_length=50)

    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )

    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)

    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )

    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')

        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()



class ProfileForm(forms.Form):
    website = forms.URLField(max_length=200, required=True)
    biography = forms.CharField(max_length=500, required=False)
    phone_number = forms.CharField(max_length=20, required=False)
    picture = forms.ImageField()

turno_app/users/views.py
# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect
from django.views.generic import DetailView, FormView, UpdateView

# Models
from django.contrib.auth.models import User
from users.models import Profile

# Forms
from users.forms import SignupForm


class UserDetailView(LoginRequiredMixin, DetailView):

    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        return context

class SignupView(FormView):
    """Users sign up view."""

    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('posts:feed')
        return super(FormView, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)

class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """Update profile view."""

    template_name = 'users/update_profile.html'
    model = Profile
    fields = ['website', 'biography', 'phone_number', 'picture']

    def get_object(self):
        """Return user's profile."""
        return self.request.user.profile

    def get_success_url(self):
        """Return to user's profile."""
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username': username})

class LoginView(auth_views.LoginView):
    """Login view."""

    template_name = 'users/login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('posts:feed')
        return super(LoginView, self).get(request, *args, **kwargs)
        

class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Logout view."""

    template_name = 'users/logged_out.html'

#######   Deprecated Methods #########
# Create your views here.
# def login_view(request):
#     if request.method == 'POST':
#         username = request.POST['username']
#         password = request.POST['password']
#         user =authenticate(request, username=username,password=password)
#         if user:
#             login(request,user)
#             return redirect('posts:feed')
#         else:
#             return render(
#                 request, 
#                 'users/login.html', 
#                 {
#                     'error': 'Invalid username and password!'
#                 })
#     else:
#         if request.user.is_authenticated:
#             return redirect('posts:feed')


#     return render(request, 'users/login.html')

# @login_required
# def logout_view(request):
#     logout(request)
#     return redirect('users:login')

# def signup(request):
#     """Sign up view."""
#     if request.method == 'POST':
#         form = SignupForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('users:login')
#     else:
#         if request.user.is_authenticated:
#             return redirect('posts:feed')

#         form = SignupForm()

#     return render(
#         request=request,
#         template_name='users/signup.html',
#         context={'form': form}
#     )

# def signup(request):

#     if request.method == 'POST':
#         username = request.POST['username']
#         passwd = request.POST['passwd']
#         passwd_confirmation = request.POST['passwd_confirmation']

#         if passwd != passwd_confirmation:
#             return render(
#                 request, 
#                 'users/signup.html',
#                 {
#                     'error': 'Password confirmation does not match!'
#                 })
#         else:
#             try:
#                 user = User.objects.create_user(username=username, password=passwd)
#             except IntegrityError as ie:
#                 print(ie)
#                 return render(request, 'users/signup.html', { 'error': 'Username is already in user!'})
            
#             user.first_name = request.POST['first_name']
#             user.last_name = request.POST['last_name']
#             user.email = request.POST['email']
#             user.save()

#             profile = Profile(user=user)
#             profile.save()

#             return redirect('users:login')
#     else:
#         if request.user.is_authenticated:
#             return redirect('posts:feed')

#     return render(request, 'users/signup.html')

# @login_required
# def update_profile(request):

#     try:
#         profile = request.user.profile
#     except ObjectDoesNotExist:
#         profile = dict()

#     if  request.method == 'POST':
#         form = ProfileForm(request.POST,request.FILES)
#         if form.is_valid():
#             data = form.cleaned_data

#             profile.website = data['website']
#             profile.phone_number = data['phone_number']
#             profile.biography = data['biography']
#             profile.picture = data['picture']
#             profile.save()

#             url = reverse('users:detail',kwargs={'username' : request.user.username})
#             return redirect(url)
#     else:
#         form = ProfileForm()

#     return render(
#         request=request,
#         template_name='users/update_profile.html',
#         context={
#             'profile': profile,
#             'user': request.user,
#             'form': form
#         }
#     )

turno_app/templates/users/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <title>
    Turno App | {% block title %}{% endblock %}
  </title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
  <link rel="stylesheet" href="{% static 'css/main.css' %}" />

  <link rel="apple-touch-icon" sizes="57x57" href="{% static 'img/favicon/apple-icon-57x57.png' %}">
  <link rel="apple-touch-icon" sizes="60x60" href="{% static 'img/favicon/apple-icon-60x60.png' %}">
  <link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/favicon/apple-icon-72x72.png' %}">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/favicon/apple-icon-76x76.png' %}">
  <link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/favicon/apple-icon-114x114.png' %}">
  <link rel="apple-touch-icon" sizes="120x120" href="{% static 'img/favicon/apple-icon-120x120.png' %}">
  <link rel="apple-touch-icon" sizes="144x144" href="{% static 'img/favicon/apple-icon-144x144.png' %}">
  <link rel="apple-touch-icon" sizes="152x152" href="{% static 'img/favicon/apple-icon-152x152.png' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon/apple-icon-180x180.png' %}">
  <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'img/favicon/android-icon-192x192.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon/favicon-96x96.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'img/favicon/manifest.json' %}">

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
</head>

<body class="h-100">
  <div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
      <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">
        <img src="{% static 'img/logo.png' %}" class="img-fluid rounded
          mx-auto d-block pb-4" style="max-width: 60%;" />
        {% block container %}{% endblock%}
      </div>
    </div>
  </div>
</body>

</html>

turno_app/templates/users/detail.html
{% extends "base.html" %} {% block head_content %}
<title>@{{ user.username }} | Platzigram</title>
{% endblock %} {% block container %}

<div class="container mb-5" style="margin-top: 8em;">
  <div class="row">
    <div class="col-sm-4 d-flex justify-content-center">
      <img
        src="{{ user.profile.picture.url }}"
        alt="@{{ user.username}}"
        class="rounded-circle"
        width="150px"
      />
    </div>
    <div class="col-sm-8">
      <h2 style="font-weight: 100;">
        {{ user.username }} {% if user == request.user %}
        <a
          href="{% url 'users:update_profile' %}"
          class="ml-5 btn btn-sm btn-outline-info"
        >
          Edit profile
        </a>
        {% else %}
        <a href="" class="ml-5 btn btn-sm btn-primary">
          Follow
        </a>
        {% endif %}
      </h2>
      <div class="row mt-2" style="font-size: 1.2em">
        <div class="col-sm-4">
          <b>{{ user.profile.posts_count }}785</b> posts
        </div>
        <div class="col-sm-4">
          <b>{{ user.profile.followers }}1,401</b> followers
        </div>
        <div class="col-sm-4">
          <b>{{ user.profile.following }}491</b> following
        </div>
      </div>
      <div class="row mt-4">
        <div class="col-sm-12">
          <p>{{ user.profile.biography }}</p>
        </div>
      </div>
    </div>
  </div>
</div>

<hr />

<div class="container" id="user-posts">
  <div class="row mt-3">
    {% for post in posts %}
    <div
      class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center"
    >
      <a href="{% url 'posts:detail' post.pk %}" class="border">
        <img
          src="{{ post.photo.url }}"
          alt="{{ post.title }}"
          class="img-fluid"
        />
      </a>
    </div>
    {% empty %}
    <div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
      <div class="media pt-3 pl-3 pb-1">
        <div class="media-body">
          <p style="margin-top: 5px;">
            {% if user == request.user %} You have no posts!
            <a href="{% url 'posts:create_post' %}">Create your first post!</a>
            {% else %} {{ user.username }} has no Posts! {% endif %}
          </p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

turno_app/templates/users/login.html
{% extends "users/base.html" %}

{% block title %}
    Iniciar Sesion
{% endblock%}

{% block container %}

{% if form.errors %}
<div class="alert alert-danger">
    Tu Usuario y Contraseña no existen en nuestra applicacion.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif%}

<form method="POST" action="{% url 'users:login' %}">
    {% csrf_token %}

    <div class="form-group">
        <input type="text" class="form-control" placeholder="Usuario" name="username" />
    </div>
    <div class="form-group">
        <input type="password" class="form-control" placeholder="Contraseña" name="password" />
    </div>
    <button type="submit" class="btn btn-primary btn-block mt-5">Iniciar Sesion!</button>

</form>
<!-- <p class="mt-4">Don't have an account yet? <a href="{% url 'users:signup' %}">Registrate</a></p> -->

{% endblock %}

turno_app/templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Platzigram sign up</title>
{% endblock%}

{% block container %}

<!-- {% if error %}
<p class="alert alert-danger">{{ error }}</p>
{% endif%} -->

<form action="{% url 'users:signup' %}" method="POST">
    {% csrf_token %}
<!-- 
    <div class="form-group">
        <input class="form-control" type="text" placeholder="Username" name="username" required="true" />
    </div>

    <div class="form-group">
        <input class="form-control" type="password" placeholder="Password" name="passwd" required="true" />
    </div>

    <div class="form-group">
        <input class="form-control" type="password" placeholder="Password confirmation" name="passwd_confirmation"
            required="true" />
    </div>

    <div class="form-group">
        <input class="form-control" type="text" placeholder="First name" name="first_name" required="true" />
    </div>

    <div class="form-group">
        <input class="form-control" type="text" placeholder="Last name" name="last_name" required="true" />
    </div>

    <div class="form-group">
        <input class="form-control" type="email" placeholder="Email address" name="email" required="true" />
    </div> -->

    {{ form.as_p }}

    <button class="btn btn-primary btn-block mt-5" type="submit">Register!</button>

</form>

<p class="mt-4"> <a href="{% url 'users:login' %}">Sign In!</a></p>


{% endblock %}

turno_app/templates/users/update_profile.html
{% extends "base.html" %} {% load static %} {% block head_content %}
<title>@{{ request.user.username }} | Update profile</title>
{% endblock %} {% block container %}

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-6 p-4" id="profile-box">
      <form
        action="{% url 'users:update_profile' %}"
        method="POST"
        enctype="multipart/form-data"
      >
        {% csrf_token %}
        <!-- {% if form.errors %}
        <p class="alert alert-danger">{{ form.errors }}</p>
        {% endif %} -->

        <div class="media">
          {% if profile.picture %}
          <img
            src="{{ profile.picture.url }}"
            class="rounded-circle"
            height="50"
            alt="{{ request.user.username }}"
          />
          {% else%}
          <img
            src="{% static 'img/default-profile.png' %}"
            class="rounded-circle"
            height="50"
          />
          {% endif %}

          <div class="media-body">
            <h5 class="ml-4">
              @{{ user.username }} | {{ user.get_full_name }}
            </h5>
            <p class="ml-4"><input type="file" name="picture" /></p>
          </div>
        </div>
        {% for error in form.picture.errors %}
        <div class="alert alert-danger"><b>Picture: </b>{{ error }}</div>
        {% endfor %}
        <hr />
        <br />

        <div class="form-group">
          <label>Website</label>
          <input
            class="form-control {% if form.website.errors %} is-invalid {% endif %}"
            type="url"
            name="website"
            placeholder="Website"
            value="{% if form.errors %} {{form.website.value}} {% else %} {{ profile.website }} {% endif %}"
          />
          <div class="invalid-feedback">
            {% for error in form.website.errors %} {{ error }} {% endfor %}
          </div>
        </div>

        <div class="form-group">
          <label>Biography</label>
          <textarea
            class="form-control {% if form.biography.errors %} is-invalid {% endif %}"
            name="biography"
          >
{% if form.errors %} {{form.biography.value}} {% else %} {{ profile.biography }} {% endif %}
          </textarea>
          <div class="invalid-feedback">
            {% for error in form.biography.errors %} {{ error }} {% endfor %}
          </div>
        </div>

        <div class="form-group">
          <label>Phone number</label>
          <input
            class="form-control {% if form.phone_number.errors %} is-invalid {% endif %}"
            type="text"
            name="phone_number"
            placeholder="Phone number"
            value="{% if form.errors %} {{form.phone_number.value}} {% else %} {{ profile.phone_number }} {% endif %}"
          />
          <div class="invalid-feedback">
            {% for error in form.phone_number.errors %} {{ error }} {% endfor %}
          </div>
        </div>

        <button type="submit" class="btn btn-primary btn-block mt-5">
          Update info
        </button>
      </form>
    </div>
  </div>
</div>

{% endblock %}